language: python
python:
  - "3.6"
script: bash runTests.sh
branches:
  only:
    - master
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gfortran
  - mkdir bin
  - gfortran dynacv6_0.f -o bin/dynacv6_0
  - export PATH=`pwd`/bin:$PATH
